name: Build PlusOS Lite

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y nasm gcc-multilib make binutils

      # 👉 если у тебя папка "Lite"
      - name: Debug files
        run: ls -R

      - name: Build OS
        run: |
          # если проект в папке "PlusOS Lite"
          if [ -d "PlusOS Lite" ]; then
            cd "PlusOS Lite"
          fi

          make
