name: Build PlusOS Lite

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc make build-essential gcc-multilib

      - name: Build OS
        run: |
          if [ -d "PlusOS Lite" ]; then
            cd "PlusOS Lite"

            mkdir -p build

            # сборка asm (если есть)
            if [ -f boot/boot.asm ]; then
              nasm -f elf32 boot/boot.asm -o build/boot.o
            fi

            # сборка C файлов
            gcc -m32 -ffreestanding -c -Ikernel kernel/kernel.c -o build/kernel.o
            gcc -m32 -ffreestanding -c -Ikernel kernel/screen.c -o build/screen.o
            gcc -m32 -ffreestanding -c -Ikernel kernel/keyboard.c -o build/keyboard.o

            # линковка
            ld -m elf_i386 -T linker.ld -o build/os.bin build/boot.o build/kernel.o build/screen.o build/keyboard.o
          else
            echo "Folder 'PlusOS Lite' not found!"
            exit 1
          fi

      - name: Upload OS
        uses: actions/upload-artifact@v4
        with:
          name: PlusOS
          path: "PlusOS Lite/build/os.bin"
